/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/query/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_query_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all documents */
        get: operations["documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document metadata + normalized text */
        get: operations["document_detail_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunks for a document */
        get: operations["document_chunks_documents__doc_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a background sync */
        post: operations["sync_documents_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations */
        get: operations["conversations_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full conversation with per-turn citations */
        get: operations["conversation_detail_conversations__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard corpus + index stats */
        get: operations["overview_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent sync runs */
        get: operations["runs_sync_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Curated, secret-free runtime config */
        get: operations["config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieval/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a query and inspect its trace */
        post: operations["inspect_retrieval_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent trace summaries */
        get: operations["traces_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full trace record by id */
        get: operations["trace_detail_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tail of the app log */
        get: operations["logs_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List eval runs (manifest) */
        get: operations["runs_evals_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/runs/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval run meta + summary */
        get: operations["run_detail_evals_runs__tag__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/runs/{tag}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-question rows (run ⨝ scored) */
        get: operations["run_rows_evals_runs__tag__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/runs/{tag}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics diff vs a baseline run */
        get: operations["run_diff_evals_runs__tag__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/runs/{tag}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App-log slice for the run's time window */
        get: operations["run_logs_evals_runs__tag__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chunks/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve chunk IDs to chunks */
        post: operations["lookup_chunks_chunks_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Abstention */
        Abstention: {
            /** Correct */
            correct?: number | null;
            /** Total */
            total?: number | null;
            /** Abstain Count */
            abstain_count?: number | null;
            /** Accuracy */
            accuracy?: number | null;
        };
        /** AbstentionDiff */
        AbstentionDiff: {
            /** Candidate */
            candidate?: number | null;
            /** Baseline */
            baseline?: number | null;
            /** Delta */
            delta?: number | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
            /** Debug */
            debug?: boolean | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["Source"][];
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /**
             * Error
             * @default false
             */
            error: boolean;
            /** Session Id */
            session_id: string;
        };
        /** CategoryCount */
        CategoryCount: {
            /** Category */
            category: string;
            /** Count */
            count: number;
        };
        /** CategoryDiff */
        CategoryDiff: {
            /**
             * Status
             * @enum {string}
             */
            status: "matched" | "missing_baseline" | "missing_candidate";
            candidate?: components["schemas"]["MetricSet"] | null;
            baseline?: components["schemas"]["MetricSet"] | null;
            delta?: components["schemas"]["MetricSet"] | null;
        };
        /** CategoryMetrics */
        CategoryMetrics: {
            /** Faithfulness */
            faithfulness?: number | null;
            /** Answer Relevancy */
            answer_relevancy?: number | null;
            /** Context Precision */
            context_precision?: number | null;
            /** Context Recall */
            context_recall?: number | null;
            /** N */
            n?: number | null;
        };
        /** ChunkListResponse */
        ChunkListResponse: {
            /** Doc Id */
            doc_id: string;
            /** Chunk Count */
            chunk_count: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkSummary"][];
        };
        /** ChunkLookupHit */
        ChunkLookupHit: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Chunk Index */
            chunk_index?: number | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count?: number | null;
            /** Title */
            title?: string | null;
        };
        /** ChunkLookupRequest */
        ChunkLookupRequest: {
            /** Chunk Ids */
            chunk_ids?: string[];
        };
        /** ChunkLookupResponse */
        ChunkLookupResponse: {
            /** Chunks */
            chunks: components["schemas"]["ChunkLookupHit"][];
            /** Missing */
            missing: string[];
        };
        /** ChunkSummary */
        ChunkSummary: {
            /** Chunk Id */
            chunk_id: string;
            /** Chunk Index */
            chunk_index?: number | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
            /** Token Estimate */
            token_estimate: number;
            /** Qdrant Id */
            qdrant_id?: string | null;
        };
        /** ChunkTrace */
        ChunkTrace: {
            /**
             * Chunk Id
             * @default
             */
            chunk_id: string;
            /** Score */
            score?: number | null;
            /**
             * Source Id
             * @default
             */
            source_id: string;
            /**
             * Unit Label
             * @default
             */
            unit_label: string;
            /**
             * Provision Id
             * @default
             */
            provision_id: string;
            /**
             * Expanded From Parent
             * @default false
             */
            expanded_from_parent: boolean;
            /**
             * Consolidated
             * @default
             */
            consolidated: string;
            /**
             * Dedup Merged Chunk Ids
             * @default []
             */
            dedup_merged_chunk_ids: string[];
            /**
             * Preview
             * @default
             */
            preview: string;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** ConfigView */
        ConfigView: {
            /** Profile */
            profile: string;
            /** Policy Overrides */
            policy_overrides: {
                [key: string]: unknown;
            };
            /** Env Ignored */
            env_ignored: {
                [key: string]: unknown;
            };
            /** Embedding Backend */
            embedding_backend: string;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Embedding Dim */
            embedding_dim?: number | null;
            /** Embedding Query Instruction */
            embedding_query_instruction?: string | null;
            /** Llm Model */
            llm_model: string;
            /** Strong Model */
            strong_model?: string | null;
            /**
             * Escalate Intents
             * @default []
             */
            escalate_intents: string[];
            /** Escalate On Partial Evidence */
            escalate_on_partial_evidence: boolean;
            /** Generator Backend */
            generator_backend: string;
            /** Reranker Backend */
            reranker_backend: string;
            /** Qdrant Collection */
            qdrant_collection: string;
            /** Qdrant Url */
            qdrant_url: string;
            /** Ollama Base Url */
            ollama_base_url: string;
            /** Chunk Size */
            chunk_size: number;
            /** Chunk Overlap */
            chunk_overlap: number;
            /** Min Chunks For Answer */
            min_chunks_for_answer: number;
            /** Evidence Gate */
            evidence_gate: string;
            /** Evidence Judge Model */
            evidence_judge_model: string;
            /** Corrective Retrieval Enabled */
            corrective_retrieval_enabled: boolean;
            /** Max Conversation Turns */
            max_conversation_turns: number;
            /** Router Enabled */
            router_enabled: boolean;
            /** Edge Expansion Enabled */
            edge_expansion_enabled: boolean;
            /** Answerability Gate Enabled */
            answerability_gate_enabled: boolean;
            /** Enable Query Rewriting */
            enable_query_rewriting: boolean;
            /** Faithfulness Selfcheck Enabled */
            faithfulness_selfcheck_enabled: boolean;
            /** Later Enacted Preference Enabled */
            later_enacted_preference_enabled: boolean;
            /** Aws Region */
            aws_region: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /** Session Id */
            session_id: string;
            /** Turn Count */
            turn_count: number;
            /** Turns */
            turns: components["schemas"]["ConversationTurn"][];
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationSummary"][];
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            /** Created At */
            created_at: string;
            /** Turn Count */
            turn_count: number;
        };
        /** ConversationTurn */
        ConversationTurn: {
            /** Turn Index */
            turn_index: number;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["Source"][];
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Doc Id */
            doc_id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Doc Type */
            doc_type: string;
            /** Category */
            category: string;
            /** Enabled */
            enabled: boolean;
            /** Updated At */
            updated_at?: string | null;
            /** Last Fetched */
            last_fetched?: string | null;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Status
             * @default unknown
             */
            status: string;
            /** Source Index */
            source_index?: string | null;
            /** Official Number */
            official_number?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Normalized Text */
            normalized_text: string;
            /** Content Hash */
            content_hash?: string | null;
            /** Content Length */
            content_length?: number | null;
            /** Extraction Method */
            extraction_method?: string | null;
            /** Http Status */
            http_status?: number | null;
            /** Approval Date */
            approval_date?: string | null;
            /** Effectivity Date */
            effectivity_date?: string | null;
            /** Availability */
            availability?: string | null;
            /** Structure */
            structure?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Amends
             * @default []
             */
            amends: string[];
            /**
             * Repeals
             * @default []
             */
            repeals: string[];
            /**
             * Supersedes
             * @default []
             */
            supersedes: string[];
            /**
             * Implements
             * @default []
             */
            implements: string[];
            /** Amends Namespace */
            amends_namespace?: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentSummary"][];
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Doc Id */
            doc_id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Doc Type */
            doc_type: string;
            /** Category */
            category: string;
            /** Enabled */
            enabled: boolean;
            /** Updated At */
            updated_at?: string | null;
            /** Last Fetched */
            last_fetched?: string | null;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Status
             * @default unknown
             */
            status: string;
            /** Source Index */
            source_index?: string | null;
            /** Official Number */
            official_number?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** EvalCorrective */
        EvalCorrective: {
            /** Enabled */
            enabled?: boolean | null;
            /** Fired */
            fired?: boolean | null;
            /** Added Chunks */
            added_chunks?: number | null;
            /** Baseline Selected Count */
            baseline_selected_count?: number | null;
            /** Post Selected Count */
            post_selected_count?: number | null;
            /** Max Added */
            max_added?: number | null;
        };
        /** EvalDiff */
        EvalDiff: {
            /** Candidate Tag */
            candidate_tag: string;
            /** Baseline Tag */
            baseline_tag: string;
            overall: components["schemas"]["OverallDiff"];
            abstention: components["schemas"]["AbstentionDiff"];
            /**
             * By Category
             * @default {}
             */
            by_category: {
                [key: string]: components["schemas"]["CategoryDiff"];
            };
        };
        /** EvalEvidence */
        EvalEvidence: {
            /** Verdict */
            verdict?: string | null;
            /** Method */
            method?: string | null;
            /**
             * Missing Facets
             * @default []
             */
            missing_facets: string[];
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /** EvalLogWindow */
        EvalLogWindow: {
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** EvalModelChoice */
        EvalModelChoice: {
            /** Model */
            model?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** EvalRow */
        EvalRow: {
            /** Eval Id */
            eval_id?: string | null;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Category */
            category?: string | null;
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /** Ground Truth */
            ground_truth?: string | null;
            /**
             * Contexts
             * @default []
             */
            contexts: string[];
            /** Faithfulness */
            faithfulness?: number | null;
            /** Answer Relevancy */
            answer_relevancy?: number | null;
            /** Context Precision */
            context_precision?: number | null;
            /** Context Recall */
            context_recall?: number | null;
            /** Split */
            split?: string | null;
            /** Topic */
            topic?: string | null;
            /** Facet */
            facet?: string | null;
            /** Profile */
            profile?: string | null;
            /** Generator Model */
            generator_model?: string | null;
            /** Elapsed S */
            elapsed_s?: number | null;
            /**
             * Expected Sources
             * @default []
             */
            expected_sources: string[];
            /**
             * Retrieved Sources
             * @default []
             */
            retrieved_sources: string[];
            /**
             * Cited Sources
             * @default []
             */
            cited_sources: string[];
            /**
             * Expected Missing
             * @default []
             */
            expected_missing: string[];
            /**
             * Selected Chunk Ids
             * @default []
             */
            selected_chunk_ids: string[];
            evidence?: components["schemas"]["EvalEvidence"] | null;
            corrective_retrieval?: components["schemas"]["EvalCorrective"] | null;
            model_choice?: components["schemas"]["EvalModelChoice"] | null;
            /**
             * Debug Stages
             * @default []
             */
            debug_stages: components["schemas"]["EvalStage"][];
        };
        /** EvalRowsResponse */
        EvalRowsResponse: {
            /** Tag */
            tag: string;
            /** Row Count */
            row_count: number;
            /** Scored Count */
            scored_count: number;
            /** Rows */
            rows: components["schemas"]["EvalRow"][];
            /**
             * Holdout Redacted
             * @default false
             */
            holdout_redacted: boolean;
        };
        /** EvalRunDetail */
        EvalRunDetail: {
            /** Tag */
            tag: string;
            /** Model */
            model?: string | null;
            /** Label */
            label?: string | null;
            /** Date */
            date?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Question Count */
            question_count?: number | null;
            /** Scored Count */
            scored_count?: number | null;
            summary?: components["schemas"]["EvalSummary"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** EvalRunListResponse */
        EvalRunListResponse: {
            /** Runs */
            runs: components["schemas"]["EvalRunSummary"][];
        };
        /** EvalRunLogsResponse */
        EvalRunLogsResponse: {
            /** Tag */
            tag: string;
            window?: components["schemas"]["EvalLogWindow"] | null;
            /** Entries */
            entries: components["schemas"]["LogEntry"][];
            /** Count */
            count: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Holdout Redacted
             * @default false
             */
            holdout_redacted: boolean;
        };
        /** EvalRunSummary */
        EvalRunSummary: {
            /** Tag */
            tag: string;
            /** Date */
            date?: string | null;
            /** Model */
            model?: string | null;
            /** Label */
            label?: string | null;
            /** Questions */
            questions?: number | null;
            /** Scored */
            scored?: number | null;
            /**
             * Holdout
             * @default false
             */
            holdout: boolean;
            /** Git Sha */
            git_sha?: string | null;
            /** Abstention Accuracy */
            abstention_accuracy?: number | null;
            /** Faithfulness */
            faithfulness?: number | null;
            /** Answer Relevancy */
            answer_relevancy?: number | null;
            /** Context Precision */
            context_precision?: number | null;
            /** Context Recall */
            context_recall?: number | null;
        };
        /** EvalStage */
        EvalStage: {
            /** Name */
            name: string;
            /** In N */
            in_n?: number | null;
            /** Out N */
            out_n?: number | null;
            /** Ms */
            ms?: number | null;
            /** Fired */
            fired?: boolean | null;
            /** Model */
            model?: string | null;
            /** Prompt Length */
            prompt_length?: number | null;
        };
        /** EvalSummary */
        EvalSummary: {
            overall: components["schemas"]["MetricSet"];
            abstention: components["schemas"]["Abstention"];
            /**
             * By Category
             * @default {}
             */
            by_category: {
                [key: string]: components["schemas"]["CategoryMetrics"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Qdrant */
            qdrant: boolean;
            /** Ollama */
            ollama?: boolean | null;
            /** Generator Backend */
            generator_backend: string;
        };
        /** InspectRequest */
        InspectRequest: {
            /** Question */
            question: string;
            /** Strategy */
            strategy?: ("default" | "current_law") | null;
        };
        /** InspectResponse */
        InspectResponse: {
            /** Answer */
            answer: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["Source"][];
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /**
             * Error
             * @default false
             */
            error: boolean;
            /** Error Message */
            error_message?: string | null;
            trace?: components["schemas"]["TraceRecord"] | null;
        };
        /** LogEntry */
        LogEntry: {
            /** Timestamp */
            timestamp?: string | null;
            /** Level */
            level?: string | null;
            /** Event */
            event?: string | null;
            /** Logger */
            logger?: string | null;
            /** Raw */
            raw?: string | null;
        };
        /** LogResponse */
        LogResponse: {
            /** Entries */
            entries: components["schemas"]["LogEntry"][];
            /** Count */
            count: number;
        };
        /** MetricSet */
        MetricSet: {
            /** Faithfulness */
            faithfulness?: number | null;
            /** Answer Relevancy */
            answer_relevancy?: number | null;
            /** Context Precision */
            context_precision?: number | null;
            /** Context Recall */
            context_recall?: number | null;
        };
        /** OverallDiff */
        OverallDiff: {
            candidate: components["schemas"]["MetricSet"];
            baseline: components["schemas"]["MetricSet"];
            delta: components["schemas"]["MetricSet"];
        };
        /** Source */
        Source: {
            /** Ref */
            ref: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source Id */
            source_id: string;
            /** Locator */
            locator?: string | null;
            /** Via */
            via?: string | null;
        };
        /** StatsOverview */
        StatsOverview: {
            /** Documents Total */
            documents_total: number;
            /** Documents Enabled */
            documents_enabled: number;
            /** Chunks Total */
            chunks_total: number;
            /** Conversations Total */
            conversations_total: number;
            /** Qdrant Points */
            qdrant_points?: number | null;
            /**
             * By Category
             * @default []
             */
            by_category: components["schemas"]["CategoryCount"][];
            last_sync?: components["schemas"]["SyncRunSummary"] | null;
        };
        /** SyncRunListResponse */
        SyncRunListResponse: {
            /** Runs */
            runs: components["schemas"]["SyncRunSummary"][];
        };
        /** SyncRunSummary */
        SyncRunSummary: {
            /** Sync Run Id */
            sync_run_id: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Status */
            status?: string | null;
            /** Scanned Count */
            scanned_count?: number | null;
            /** Changed Count */
            changed_count?: number | null;
            /** Unchanged Count */
            unchanged_count?: number | null;
            /** Failed Count */
            failed_count?: number | null;
        };
        /** SyncStartedResponse */
        SyncStartedResponse: {
            /** Status */
            status: string;
            /** Sync Run Id */
            sync_run_id: string;
        };
        /** TraceListResponse */
        TraceListResponse: {
            /** Traces */
            traces: components["schemas"]["TraceSummary"][];
        };
        /** TraceRecord */
        TraceRecord: {
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /** Trace Label */
            trace_label?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Question
             * @default
             */
            question: string;
            /**
             * Rewritten Question
             * @default
             */
            rewritten_question: string;
            /**
             * Stage Counts
             * @default {}
             */
            stage_counts: {
                [key: string]: number;
            };
            /**
             * Retrieved Chunks
             * @default []
             */
            retrieved_chunks: components["schemas"]["ChunkTrace"][];
            /**
             * Pre Expansion Chunks
             * @default []
             */
            pre_expansion_chunks: components["schemas"]["ChunkTrace"][];
            /**
             * Selected Chunks
             * @default []
             */
            selected_chunks: components["schemas"]["ChunkTrace"][];
            /**
             * Retrieval Strategy
             * @default {}
             */
            retrieval_strategy: {
                [key: string]: unknown;
            };
            /**
             * Intent Router
             * @default {}
             */
            intent_router: {
                [key: string]: unknown;
            };
            /**
             * Feature Flags
             * @default {}
             */
            feature_flags: {
                [key: string]: unknown;
            };
            /** Profile */
            profile?: string | null;
            /**
             * Policy
             * @default {}
             */
            policy: {
                [key: string]: unknown;
            };
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /**
             * Error
             * @default false
             */
            error: boolean;
            /**
             * Stages
             * @default []
             */
            stages: unknown[];
            /** Latency Ms */
            latency_ms?: number | null;
            /** Prompt Length */
            prompt_length?: number | null;
            /** Generator Model */
            generator_model?: string | null;
            /** Model Choice */
            model_choice?: {
                [key: string]: unknown;
            } | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            } | null;
            /** Corrective Retrieval */
            corrective_retrieval?: {
                [key: string]: unknown;
            } | null;
        };
        /** TraceSummary */
        TraceSummary: {
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /** Timestamp */
            timestamp?: string | null;
            /** Trace Label */
            trace_label?: string | null;
            /**
             * Question
             * @default
             */
            question: string;
            /** Strategy */
            strategy?: string | null;
            /**
             * Stage Counts
             * @default {}
             */
            stage_counts: {
                [key: string]: number;
            };
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /**
             * Error
             * @default false
             */
            error: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_query_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthcheck_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
        };
    };
    document_detail_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_chunks_documents__doc_id__chunks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_documents_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStartedResponse"];
                };
            };
        };
    };
    conversations_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    conversation_detail_conversations__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverview"];
                };
            };
        };
    };
    runs_sync_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    inspect_retrieval_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traces_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_detail_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logs_logs_get: {
        parameters: {
            query?: {
                lines?: number;
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_evals_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunListResponse"];
                };
            };
        };
    };
    run_detail_evals_runs__tag__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_rows_evals_runs__tag__rows_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_diff_evals_runs__tag__diff_get: {
        parameters: {
            query: {
                baseline: string;
            };
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_logs_evals_runs__tag__logs_get: {
        parameters: {
            query?: {
                level?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_chunks_chunks_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkLookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
